#cloud-config
users:
  - default
  - name: kcore
    gecos: Kcore Operator
    groups: [sudo]
    shell: /bin/bash
    lock_passwd: true
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJwK8T9OAIGS4/e+m2jT1aFhrkkthbyX6d5V4gADFD9+ rtacconi@nixos1
ssh_pwauth: false
disable_root: true
package_update: true
runcmd:
  - [sh, -c, "cloud-init status --wait || true"]
